import sys

env = Environment()

if sys.platform == "linux2":
  ccflags = '-Wall -ansi -g'
else:
  ccflags = '/EHsc /MD /GR'

env.Append(CCFLAGS = ccflags)

sources = Split('TestsRunner.cxx MiniCppUnit.cxx UsageExample.cxx')

env.Program( sources )

