/********************************************************************
	Generated by Sexy Kanji Resource Generator (JPoag/HFischer)
	-----------------------------------------------------------
	Created:	26.04.2010 10:14:30
	Filename:	Res.h

	Purpose:	Functions and globals, based on the resource.xml file,
				to easily use the resources in your program.
*********************************************************************/

#ifndef __RES_H__
#define __RES_H__

#include "Common.h"

namespace Sexy
{
	// forward declarations
	class ResourceManager;
	class SexyImage;
	class SexyFont;
	class SexyMovie;

	SexyImage* LoadImageById(ResourceManager* theManager, int theId);
	void ReplaceImageById(ResourceManager* theManager, int theId, SexyImage* theImage);
	bool ExtractResourcesByName(ResourceManager* theManager, SexyString theName);

	// Game Resources

	bool ExtractGameResources(ResourceManager* theMgr);

	extern SexyImage* IMAGE_CHECKBOX;
	extern SexyImage* IMAGE_ROBOTROBOT;

	// Init Resources

	bool ExtractInitResources(ResourceManager* theMgr);

	extern int MUSIC_GROOVE;
	extern SexyFont* FONT_DEFAULT;
	extern SexyImage* IMAGE_CUSTOM_DRAGGING;
	extern SexyImage* IMAGE_CUSTOM_HAND;
	extern SexyImage* IMAGE_CUSTOM_POINTER;
	extern SexyImage* IMAGE_CUSTOM_TEXT;
	extern SexyImage* IMAGE_KANJI_LOGO;

	// TitleScreen Resources

	bool ExtractTitleScreenResources(ResourceManager* theMgr);

	extern SexyImage* IMAGE_LOADER_BAR;
	extern SexyImage* IMAGE_LOADER_LOADINGTXT;

	// Resource IDs

	enum ResourceId
	{
		FONT_DEFAULT_ID,
		IMAGE_CUSTOM_POINTER_ID,
		IMAGE_CUSTOM_HAND_ID,
		IMAGE_CUSTOM_DRAGGING_ID,
		IMAGE_CUSTOM_TEXT_ID,
		IMAGE_KANJI_LOGO_ID,
		MUSIC_GROOVE_ID,
		IMAGE_LOADER_BAR_ID,
		IMAGE_LOADER_LOADINGTXT_ID,
		IMAGE_ROBOTROBOT_ID,
		IMAGE_CHECKBOX_ID,
		RESOURCE_ID_MAX
	};

	// Getter functions

	SexyImage* GetImageById(int theId);
	SexyFont* GetFontById(int theId);
	int GetSoundById(int theId);
	int GetMusicById(int theId);
	SexyMovie* GetMovieById(int theId);

	SexyImage*& GetImageRefById(int theId);
	SexyFont*& GetFontRefById(int theId);
	int& GetSoundRefById(int theId);
	int& GetMusicRefById(int theId);
	SexyMovie*& GetMovieRefById(int theId);

	ResourceId GetIdByImage(SexyImage* theImage);
	ResourceId GetIdByFont(SexyFont* theFont);
	ResourceId GetIdBySound(int theSound);
	ResourceId GetIdByMusic(int theMusic);
	ResourceId GetIdByMovie(SexyMovie* theMovie);

	SexyString GetStringIdById(int theId);
	ResourceId GetIdByStringId(SexyString theStringId);

} // namespace Sexy

#endif // __RES_H__
